training_common:
  dataset_path: /home2/lie/InnovativePractice2/data/kitti/tracking/extracted_points_official_label_1
  ckpt_out_path: /home2/lie/zhangsh/InnovativePractice1_SUSTech/OurNet/checkpoints/sizeNet/
  training_parameters:
    epochs: 10000
    batch_size: 32
    shuffle: True
    workers: 4
    cudaidx: 3
    train_ratio: 0.8
    early_stop: True
    learning_rate: 0.001

pillar_cfg:
  USE_NORM: True # whether batchNormalization
  WITH_DISTANCE: False # default false
  USE_ABSLOTE_XYZ: True # default true
  NUM_FILTERS: # channel output of every CNN, (bev's feature)
    - 64