visualize_root:
  pointspath: "/home/zrh/Data/kitti/data_tracking_velodyne/0000/000000.bin"
  objectpath: "/home/zrh/Data/kitti/tracking/extracted_points/0000/Van#0/points/000000.npy"
  objectpath2: "/home/zrh/Data/kitti/tracking/extracted_points/0000/Van#0/points/000001.npy"
  boxpath: "/home/zrh/Data/kitti/data_tracking_label_2/training/label_2/0000.txt"  # label's path (in object format)
  calibpath: "/home/zrh/Data/kitti/data_tracking_calib/training/calib/0000.txt"

extract_root:
  labelroot: "/home/zrh/Data/kitti/data_tracking_label_2/training/label_02/"
  calibroot: "/home/zrh/Data/kitti/data_tracking_calib/training/calib/"
  pointroot: "/home/zrh/Data/kitti/data_tracking_velodyne/"
  outputroot: "/home/zrh/Data/kitti/tracking/extracted_points"