#! /bin/bash
# if have data in format of kitti tracking data, you should use this to transition object detection results
# to tracking result with trajectory ID.
# @Input:
#   1. object labels: generated by PV_RCNN using tracking data in object format which is trained by train.py
#                     but all of them are set as validation data
# @Output:
#   2. tracking label: generated by ABMOT

transitionScript=object2AB3dMOT.py
scriptRoot=../format_utils

ABMOTRoot=1

# transition data
cd ${scriptRoot} || return
python ${transitionScript}

# run ABMOT




